---
name:Checks 

on: [push]

jobs:
  test-lint:
    name: Testing and Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: Docker/login-action@v1
        with: 
          username : {{secrets.DOCKERHUB_USER}}
          password : {{secrets.DOCKERHUB_TOKEN}}
    
      - name : Checkout
        uses : actions.checkout@v2

      - name : Testing
        test : docker-compose run -rm app sh -c "python manage.py test"

      - name : Linting
        run : docker-compose run -rm app sh -c "flake8"